---
- name: Installing multiple packages
  hosts: all
  become: true
  tasks:
  - name: Installing multiple packages
    user:
      name: "{{item}}"
      state: present
    with_items:
      - user1
      - user2
      - user3
      - user4
      - user5
      - user6 


