---
- name: Installing httpd  
  hosts: all
  become: true 
  tasks: 
  - name: Installing a package httpd
    yum: 
      name: httpd 
      state: installed

  - name: Start service httpd 
    service:
      name: httpd
      state: started

