---
- name: Installing apache
  hosts: all
  become: true
  tasks:
  - name: Install httpd package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"
    tags: install_apacche

  - name: Start httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
    tags: start_apche

  - name: Install apache2 package
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
        tags: install_apacche

  - name: Start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
    tags: start_apche

  - name: copy index.html
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/index.html
      mode: 0777

